# example profiles.yml file
jaffle_shop:
  target: dev 
  outputs:
    dev:
      type: postgres
      host: localhost
      user: airflow
      password: airflow
      port: 5432
      dbname: jaffle_shop
      schema: dbt_dev
      threads: 1

    trino:
      type: trino
      method: none
      user: admin
      password:
      database: iceberg
      schema: jaffle_shop
      host: localhost
      port: 8080
      http_scheme: http
      threads: 1